//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permisos.Común {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Permisos.Común.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos del empleados.
        /// </summary>
        public static string ApellidosEmpleado {
            get {
                return ResourceManager.GetString("ApellidosEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los apellidos no pueden ser mayor a 100 caracteres..
        /// </summary>
        public static string ApellidosEmpleadoErrorMuyLargo {
            get {
                return ResourceManager.GetString("ApellidosEmpleadoErrorMuyLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe introducir los apellidos del empleado..
        /// </summary>
        public static string ApellidosEmpleadoErrorNulo {
            get {
                return ResourceManager.GetString("ApellidosEmpleadoErrorNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha del permiso.
        /// </summary>
        public static string FechaPermiso {
            get {
                return ResourceManager.GetString("FechaPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha debe tener un formato &quot;yyyy/MM/dd&quot;..
        /// </summary>
        public static string FechaPermisoErrorDatosInvalidos {
            get {
                return ResourceManager.GetString("FechaPermisoErrorDatosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha debe ser major a &quot;Enero 1 1753&quot;..
        /// </summary>
        public static string FechaPermisoErrorFechaMuyAntigua {
            get {
                return ResourceManager.GetString("FechaPermisoErrorFechaMuyAntigua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe seleccionar la fecha del permiso..
        /// </summary>
        public static string FechaPermisoErrorNulo {
            get {
                return ResourceManager.GetString("FechaPermisoErrorNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del empleado.
        /// </summary>
        public static string NombreEmpleado {
            get {
                return ResourceManager.GetString("NombreEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no puede ser mayor a 100 caracteres..
        /// </summary>
        public static string NombreEmpleadoErrorMuyLargo {
            get {
                return ResourceManager.GetString("NombreEmpleadoErrorMuyLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe introducir el nombre del empleado..
        /// </summary>
        public static string NombreEmpleadoErrorNulo {
            get {
                return ResourceManager.GetString("NombreEmpleadoErrorNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de permiso.
        /// </summary>
        public static string TipoPermiso {
            get {
                return ResourceManager.GetString("TipoPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe seleccionar el tipo de permiso..
        /// </summary>
        public static string TipoPermisoErrorNulo {
            get {
                return ResourceManager.GetString("TipoPermisoErrorNulo", resourceCulture);
            }
        }
    }
}
